In [1]:
import torch

# Here we start by creating the original Database with 5000 entries

num_entries = 5000

db = torch.rand(num_entries) > 0.5
db

tensor([ True,  True, False,  ...,  True,  True, False])

In [2]:
# now we can obtain a parallel database by removing an entry from the database with the help of slicing and concatenation

remove_index = 2 #index that we're gonna remove

db[0:5] #first five entries of the database before slicing

tensor([ True,  True, False,  True,  True])

In [3]:
torch.cat((db[0:2], db[3:]))[0:5] #generates a parallel database

tensor([True, True, True, True, True])

In [4]:
# incorporating the above functionality in a function that we can call

def get_parallel_db(db, remove_index):
    return torch.cat((db[0:remove_index], db[remove_index+1:]))

In [6]:
get_parallel_db(db, 3) #testing our function

torch.Size([4999])

In [7]:
# Now we write a function that goes through each element of our database 
# and generates a parallel database with that element removed
# But first we create list for storing all the parallel databases

def get_parallel_dbs(db):
    
    parallel_dbs = list()
    
    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_dbs.append(pdb)
    
    return parallel_dbs

In [8]:
pdbs = get_parallel_dbs(db)

In [12]:
len(pdbs)

5000

In [13]:
# Finally we incorporate all the above functionality into one function

def create_db_and_parallels(num_entries):
    
    db = torch.rand(num_entries) > 0.5
    
    return get_parallel_dbs(db)

In [14]:
pdbs = create_db_and_parallels(20)

In [15]:
pdbs

[tensor([ True, False, False,  True, False,  True, False,  True,  True,  True,
          True,  True, False,  True, False,  True,  True,  True,  True]),
 tensor([False, False, False,  True, False,  True, False,  True,  True,  True,
          True,  True, False,  True, False,  True,  True,  True,  True]),
 tensor([False,  True, False,  True, False,  True, False,  True,  True,  True,
          True,  True, False,  True, False,  True,  True,  True,  True]),
 tensor([False,  True, False,  True, False,  True, False,  True,  True,  True,
          True,  True, False,  True, False,  True,  True,  True,  True]),
 tensor([False,  True, False, False, False,  True, False,  True,  True,  True,
          True,  True, False,  True, False,  True,  True,  True,  True]),
 tensor([False,  True, False, False,  True,  True, False,  True,  True,  True,
          True,  True, False,  True, False,  True,  True,  True,  True]),
 tensor([False,  True, False, False,  True, False, False,  True,  True,  True,
   